# Sentiment Analysis using twitter

In [1]:
import pandas as pd

In [4]:
train = pd.read_csv('train.csv', encoding = 'ISO-8859-1')

In [5]:
train.head()

ItemID  Sentiment                                      SentimentText
0       1          0                       is so sad for my APL frie...
1       2          0                     I missed the New Moon trail...
2       3          1                            omg its already 7:30 :O
3       4          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4       5          0           i think mi bf is cheating on me!!!   ...

-encoding
-characters to computers
-ASCII, UNICODE(utf-8), ISO

# -pull out some numbers
- sentiment 0 is sad sentence
- sentiment 1 is happy sentence

In [8]:
train['Sentiment'].value_counts()

1    56457
0    43532
Name: Sentiment, dtype: int64

# Sentiment Analysis Algorithm

-spam or not spam
-spam[word1,word2,word3]
-not spam[word1,word2,word3]
-email- word by word numbers of words in  spam, number of words not in spam 
- domain specific problem
 

# Top 10 words present in our positive tweets. 


In [11]:
from nltk.tokenize import TweetTokenizer
tk = TweetTokenizer()

In [ ]:
tk.tokenize(text)

In [12]:
from nltk.probability import FreqDist

In [ ]:
fdist = FreqDist(tokens)

In [13]:
all_positives = train[train.Sentiment == 1]# fitering our data

In [14]:
all_positives.head()

ItemID  Sentiment                                      SentimentText
2        3          1                            omg its already 7:30 :O
6        7          1                 Juuuuuuuuuuuuuuuuussssst Chillin!!
8        9          1        handed in my uniform today . i miss you ...
9       10          1           hmmmm.... i wonder how she my number @-)
11      12          1        thanks to all the haters up in my face a...

In [17]:
whole_text = ' '.join(all_positives.SentimentText.values)

In [19]:
#whole_text

In [26]:
pos_tokens = tk.tokenize(whole_text)

In [23]:
#pos_tokens
#use stop words
from nltk.corpus import stopwords
stop_word = stopwords.words('english')

In [27]:
pos_token_wo_sw = [each for each in pos_tokens if each.lower() not in stop_word]

In [45]:
fdist_wo_sw = FreqDist(pos_token_wo_sw)
fdist_wo_sw.most_common(30)

[('!', 34630),
 ('.', 26592),
 (',', 19659),
 ('?', 12692),
 ('...', 8361),
 ('"', 6207),
 ('-', 4534),
 ('..', 3428),
 ('good', 3381),
 ("I'm", 3282),
 ('like', 3049),
 ('love', 2833),
 ('u', 2642),
 ('know', 2389),
 ('get', 2365),
 ('*', 2315),
 ('lol', 2050),
 ('thanks', 2007),
 ('one', 1907),
 ('day', 1854),
 (':', 1822),
 ('&', 1813),
 (')', 1797),
 ('see', 1747),
 ("'", 1738),
 ('(', 1672),
 ('time', 1623),
 ('well', 1594),
 ('haha', 1593),
 ('think', 1550)]

# Top 10 words present in our negative tweets.

In [30]:
all_negative = train[train.Sentiment == 0]

In [32]:
all_negative.head()

ItemID  Sentiment                                      SentimentText
0       1          0                       is so sad for my APL frie...
1       2          0                     I missed the New Moon trail...
3       4          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4       5          0           i think mi bf is cheating on me!!!   ...
5       6          0                  or i just worry too much?

In [37]:
text = ' '.join(all_negative.SentimentText.values)

In [38]:
neg_tokens = tk.tokenize(text)

In [40]:
#neg_tokens
#now removing stop words

In [41]:
neg_token_wo_sw = [each for each in neg_tokens if each.lower() not in stop_word]

In [43]:
fdist_neg_wo_sw = FreqDist(neg_token_wo_sw)

In [44]:
fdist_neg_wo_sw .most_common(30)

[('.', 24191),
 ('!', 20487),
 (',', 12919),
 ('?', 9207),
 ('...', 8468),
 ("I'm", 3366),
 ('..', 2979),
 ('"', 2948),
 ('*', 2651),
 ('get', 2562),
 ('-', 2474),
 ('like', 2300),
 ('know', 2102),
 ('u', 2009),
 ('go', 1971),
 ('work', 1618),
 ('sorry', 1570),
 ('one', 1536),
 ('miss', 1523),
 ('good', 1486),
 ('lol', 1484),
 ('got', 1474),
 ("can't", 1462),
 ('sad', 1374),
 ('really', 1374),
 ('im', 1372),
 ('going', 1366),
 ('&', 1347),
 ('want', 1320),
 ('see', 1316)]

# count Vectorizer

In [55]:
corpus = ['This is the first document first document',
         'This document is the second document',
         'And this the third one',
         'Is this the first document']

In [56]:
from sklearn.feature_extraction.text import CountVectorizer

In [57]:
vectorizer = CountVectorizer()

In [58]:
X = vectorizer.fit_transform(corpus)

In [59]:
X

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [60]:
print(vectorizer.get_feature_names())
print(X.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 2 2 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 0 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


# First Sentiment Analysis Model

In [ ]:
#convert tweet data in matrix form

In [61]:
count_vec = CountVectorizer(stop_words = 'english',ngram_range = (1,2))
X_train_counts = count_vec.fit_transform(train.SentimentText)

In [62]:
X_train_counts

<99989x568934 sparse matrix of type '<class 'numpy.int64'>'
	with 1315619 stored elements in Compressed Sparse Row format>

In [63]:
from sklearn.naive_bayes import MultinomialNB

In [64]:
algorithm = MultinomialNB()

In [65]:
trained_model = algorithm.fit(X_train_counts,train.Sentiment)

In [66]:
docs_new = ['life is beautiful','the service sucks','an aweful day',
           'the chocolate was amazing']

In [68]:
X_new_counts = count_vec.transform(docs_new)

In [70]:
predicted = trained_model.predict(X_new_counts)

In [71]:
predicted

array([1, 0, 0, 1])